export const SWAGGER_API_ROOT = 'docs';
export const SWAGGER_API_NAME = 'TRAMA BOX API';
export const SWAGGER_API_DESCRIPTION =
  'API IMPLEMENTADA NA CADEIRA DE CONCEPÇÃO E DESENVOLVIMENTO DE PRODUTOS 2022.2. NA UNIVERSIDADE FEDERAL DO CEARÁ.';
export const SWAGGER_API_CURRENT_VERSION = '1.0';
